### PR TITLE
add-string-and-timestamp-compare-choices Add string and timestamp compare choice rules, StringMatches

### PR DESCRIPTION
**Pull request by sumlbel**

### CODE REVIEW

**Review by oshikiri — CHANGES_REQUESTED** [review]
Please check CI error

(You can format codes by `npm run format`)

**Comment by sumlbel** [comment]
Hey, I have no idea why prettier check is failing.
It fixed everything on my machine. I'll dig into that a bit later

**Comment by sumlbel** [comment]
Fixed code style. Maybe it was some kind of versions mismatch

**Review by oshikiri — APPROVED** [review]

**Comment by oshikiri** [comment]
Nice work! I will release it soon

**Pull request merged**
